baseURL = "/"
languageCode = 'en-us'
title = 'Techjournal'
theme = "cactus"
ignoreFiles = ["content/templates/.*"]

[params]
description = "An Engineer's Path in the World of Infrastructure, Math and Computer Science"
mathjax = true
css = ["css/custom.css"]
logo = "images/quill-pen.png"
postsOnHomePage = 5

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "TIL"
url = "/til"
weight = 3

[[menu.main]]
name = "Active Learning"
url = "/active-learning"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5