baseURL = "/"
languageCode = 'en-us'
title = 'Techjournal'
theme = "cactus"
ignoreFiles = ["content/templates/.*"]

[params]
description = "Hey, welcome to my journal. Here I share my learnings, experiments and thoughts."
mathjax = true
css = ["css/custom.css"]
logo = "images/quill-pen.png"
postsOnHomePage = 10
mainSectionTitle = "Most Recent 10 Posts"
showAllPostsArchive = true


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "TIL"
url = "/til"
weight = 3

[[menu.main]]
name = "Active Learning"
url = "/active-learning"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5